//Define not defined class
#define NOT_DEFINED             -1

//Define unit classes
#define INFANTRY                600
#define INF_NORMAL              601
#define INF_MEDIC               602
#define INF_ENGINEER            603
#define INF_AA                  604
#define INF_AT                  605

//Define vehicle classes
#define VEHICLE                 700
#define VEH_UNARMED             701
#define VEH_TRANSPORT           702
#define VEH_AA                  703
#define VEH_AT                  704

//Define armor classes
#define ARMOR                   800
#define ARM_TANK                801
#define ARM_HUNTER              802

//Define air classes
#define AIR                     900
#define AIR_UNARMED             901
#define AIR_TRANSPORT           902
#define AIR_ATTACK              903

//Define usage classes
#define USE_AGAINST_UNITS       3201
#define USE_AGAINST_VEHICLES    3202
#define USE_AGAINST_ARMOR       3203
#define USE_AGAINST_AIR         3204
#define USE_FOR_COVER           3101
#define USE_FOR_HEALING         3102
#define USE_FOR_REPAIR          3103
